language: cpp

dist: "trusty"
branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - test

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      # compilers and build tools
      - cmake-data
      - cmake
      - clang-3.8
      - g++-5
      - gcc-5
      # actual dependencies
      - libboost-dev # required
      - libboost-system-dev # required
      - libboost-filesystem-dev # required
      - libboost-program-options-dev # required
#      - libclfft-dev # optional
      - libfftw3-dev # required
#      - libglew-dev # optional
#      - libglfw3-dev # optional
      - libhdf5-dev # optional
      - libpng++-dev # optional
#      - libxrandr-dev # optional
#      - opencl-dev # optional
      - python3.5
      - python3-pip

#compiler: # for "matrix builds" testing various configurations
#  - clang
#  - gcc

script: # set correct compiler versions first
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
    - cmake . -DCMAKE_BUILD_TYPE=Release
    - cmake --build .
    - ./inovesa --version
    - ./inovesa -T 5 -o test.h5
    - git clone https://github.com/Inovesa/Lisa.git Lisadir
    - mv Lisadir/Lisa .
    - git clone https://github.com/pcsch/InoTest.git
    - python3.5 -m pip install h5py numpy matplotlib tqdm --user
    - python3.5 -m unittest InoTest/test.py

